# Generated by Django 2.2.3 on 2019-09-07 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('servings', models.IntegerField(default=1)),
                ('diet', models.CharField(choices=[('NONE', 'None'), ('VEGETARIAN', 'Vegetarian'), ('VEGAN', 'Vegan')], default='NONE', max_length=255)),
                ('likes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('slug', models.SlugField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(default=0)),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='bellyoak.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit', models.CharField(choices=[('NONE', 'None'), ('Mass', (('GRAM', 'g (grams)'), ('KILOGRAM', 'kg (kilograms)'))), ('Volume', (('MILLILITRE', 'ml (millilitres)'), ('LITRE', 'l (litres)'), ('TEASPOON', 'tsp (teaspoons)'), ('TABLESPOON', 'tbsp (tablespoons)'), ('CUP', 'cup (cups)'), ('PINT', 'pt. (pints)')))], default='NONE', max_length=255)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='bellyoak.Recipe')),
            ],
        ),
    ]
