# Generated by Django 2.2.3 on 2019-09-08 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bellyoak', '0002_auto_20190908_0332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(choices=[('none', 'None'), ('Mass', (('gram', 'g (grams)'), ('kilogram', 'kg (kilograms)'))), ('Volume', (('millilitre', 'ml (millilitres)'), ('litre', 'l (litres)'), ('teaspoon', 'tsp (teaspoons)'), ('tablespoon', 'tbsp (tablespoons)'), ('cup', 'cup (cups)'), ('pint', 'pt. (pints)')))], default='none', max_length=255),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet',
            field=models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan')], default='none', max_length=255),
        ),
    ]
